version: '3'
services:
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build:
      context: wordpress
    stdin_open: true
    tty: true
    restart: always
    environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: ${DB_USERNAME}
        WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
        WORDPRESS_DB_NAME: ${DB_DATABASE}
        #WORDPRESS_DEBUG: 'true'
    volumes:
        - ./wordpress:/var/www/html
  swag:
    image: linuxserver/swag
    container_name: swag
    depends_on:
      - wordpress
    volumes:
      - ./config:/config
      - ./nginx/conf.d/:/config/nginx/site-confs/
    environment:
      - EMAIL=majidimanzade1@gmail.com
      - URL=kharidv2ray.top
      - SUBDOMAINS=www,
      - VALIDATION=http
      - TZ=Europe/London
      - PUID=500
      - PGID=500
    ports:
      - "443:443"
      - "80:80"
  db:
    image: mariadb:10.4
    restart: unless-stopped
    container_name: db
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAG}
      SERVICE_NAME: mariadb
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
volumes: 
  dbdata: 
    driver: local 
